<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors Condition="'$(CI)' == 'true'">true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <!-- 
      Suppressing KubernetesClient vulnerability from AspNetCore.HealthChecks.UI.
      We do not use Kubernetes features/probes in this project, so the code path is dead.
      Upgrading KubernetesClient causes the parent health check library to fail at runtime.
    -->
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-w7r3-mgwf-4mqq"/>
  </ItemGroup>
</Project>
