<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <OpenApiDocumentsDirectory>./.openapi/</OpenApiDocumentsDirectory>
    <UserSecretsId>37ec232d-f2c8-416c-b343-e6b14dd58ec3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql"/>
    <PackageReference Include="AspNetCore.HealthChecks.UI"/>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client"/>
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage"/>
    <PackageReference Include="Humanizer.Core"/>
    <PackageReference Include="Laraue.EfCoreTriggers.PostgreSql"/>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore"/>
    <PackageReference Include="MMonrad.OpenApi.NodaTime"/>
    <PackageReference Include="NetTopologySuite.IO.GeoJSON"/>
    <PackageReference Include="NodaTime"/>
    <PackageReference Include="NodaTime.Serialization.SystemTextJson"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime"/>
    <PackageReference Include="Scalar.AspNetCore"/>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
    <!-- This automatically grabs all current and future json files in that folder -->
    <None Include=".openapi\**\*.json" UpdateSourceOnBuild="true">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
